# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pr:
  branches:
    exclude:
      - dev
      - feature/*
      - qa
trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildSite
        displayName: Build Site
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Instal Node.js'
          - script: |
              sudo rm -rf node_modules/ build/ && sudo yarn install && sudo yarn pilot
            displayName: 'yarn install and build'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/build/'
              Contents: |
                $(System.DefaultWorkingDirectory)/build/**/*
              TargetFolder: '$(Build.ArtifactStagingDirectory)/output-site'
            displayName: 'Copy site files to artifact directory'
          - task: AzureCLI@2
            displayName: delete to blob
            inputs:
              azureSubscription: 'Microsoft Azure Sponsorship(c83f83a4-f7a1-4cb7-bab9-36e3b66c26ad)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage blob delete-batch --source "\$web" --account-name "etdapsadapaz"'
          - task: AzureCLI@2
            displayName: Deploy to blob
            inputs:
              azureSubscription: 'Microsoft Azure Sponsorship(c83f83a4-f7a1-4cb7-bab9-36e3b66c26ad)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage blob upload-batch -d "\$web" --account-name "etdapsadapaz" -s "$(Build.ArtifactStagingDirectory)/output-site/"'
