# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pr: none
trigger: none

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: Build
    displayName: PILOT BUILD
    jobs:
      - job: BuildSite
        displayName: Build Site
        pool:
          vmImage: 'ubuntu-20.04'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Instal Node.js'
          - script: |
              sudo rm -rf node_modules/ build/ && sudo yarn install && sudo yarn build
            displayName: 'yarn install and build'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/build/'
              Contents: |
                $(System.DefaultWorkingDirectory)/build/**/*
              TargetFolder: '$(Build.ArtifactStagingDirectory)/output-site'
            displayName: 'Copy site files to artifact directory'

          - task: AzureCLI@2
            displayName: delete to blob
            inputs:
              azureSubscription: 'pilot-subscription'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage blob delete-batch --source "\$web" --account-name "etdappilotaz"'
          - task: AzureCLI@2
            displayName: Deploy to blob
            inputs:
              azureSubscription: 'pilot-subscription'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage blob upload-batch -d "\$web" --account-name "etdappilotaz" -s "$(Build.ArtifactStagingDirectory)/output-site/"'
          - task: AzureCLI@2
            displayName: Purge CDN Endpoint
            inputs:
              azureSubscription: 'pilot-subscription'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az cdn endpoint purge --debug -n etdappilotaz  --profile-name etdappilotaz --content-paths "/*" --resource-group et-rg-sbx-pilot-az-eastus --no-wait --subscription 3921820d-6322-4993-9748-e894fc0956bf'