"use client";
import React from "react";
import { Metadata } from "next";
import FullWidth from "@emtech/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <section className='bg-dashboardBg w-full min-h-screen flex justify-center items-start'>
      <FullWidth>
        {children}
      </FullWidth>
    </section>
  );
};

export default AuthLayout;
