import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <section className='bg-grayBackGround w-screen h-screen min-h-screen flex justify-center items-center'>
      {children}
    </section>
  );
};

export default AuthLayout;
