"use client";
import React from "react";
import { Metadata } from "next";
import Sidebar from "@/pattern/templates/common/sidebar";
import FullWidth from "@emtech/ui"
import PageLayout from "@/pattern/templates/common/page-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <section className='bg-dashboardBg w-full min-h-screen flex justify-center items-start'>
      <FullWidth>
        <Sidebar />
        <PageLayout>{children}</PageLayout>
      </FullWidth>
    </section>
  );
};

export default Layout;
